### ISSUE TITLE
Поиск пользователя по uuid

### ISSUE THREAD

**Issue by mrfratello** [maxim1989/shelteredsea#13]
Ввести для пользователей поле _uuid_. желательно, чтобы оно было численное, но длинное (от 8 символов).
Значение этого поля также должно выдаваться, при запросе на авторизованность пользователя.
Подготовить ответ на запрос на поиск пользователя по _uuid_. Входной параметр  строка с _uuid_. На выходе параметры пользователя, у которого этот _uuid_ **совпадает полностью**

**Comment by mrfratello** [comment]
сократить размер uid_for_client до 15 разрядов (вроде это уникальность на 100 лет).
по personalarea/uid всегда возвращать список: [] - если нет совпадения
[{...}] - если было совпадение.
К возвращаемым данным добавить параметр is_fiend - является ли пользователь другом авторизованного пользователя.

**Comment by maxim1989** [comment]
использовать библиотеку uuid:
```
import uuid
uid = uuid.uuid1()
uid = uid.int
uid = uid >> 64
```
