### ISSUE TITLE
Споры

### ISSUE THREAD

**Issue by maxim1989** [maxim1989/shelteredsea#22]
- [x] создать БД

- [x] прописать url-ы (частично)

- [x] Добавить классификатор, скорректировать БД

- [x] Добавить запрос на сделку

- [x] Функция поиска

- [x] Повторяющийся запрос

- [x] кнопка next

- [x] При выводе списка игр не надо проверять пользователя на авторизованность

- [x] В таблице Game поле namespace сделать уникальным

- [x] Выводданных по одной игре (через namespace)

- [x] запрос на получение условий сделки соперника

- [x]  таблица с бубликами

- [x] поставить, наверное заглушку, что при регистрации начислять 400 бубликов

- [x] Сделать таблицу SteamGame.  Deal к SteamGame = 1 ко многим

- [x]  чат соперников (Уточнить, уже реализация есть)

- [x] подтверждение/отклонение предложения

- [x] Кнопка старт сделки

- [x] Исправить деньги в сделке на интервал от до

- [x] Отмена сделки (Временной)

**Comment by mrfratello** [comment]
При выводе списка игр не надо проверять пользователя на авторизованность
